Support for lossy MachO parsing
m4b/goblin pull request #386
Opened 2024-01-05 08:21 UTC by h33p

Made it possible to parse MachO objects in less strict manner. However, default behavior is not changed. Therefore, there now is a new function `parse_2` which accepts additional argument for lossyness.

Open questions:

- Is the default behavior intended? If not, `parse_2` could be made private.
- Is `parse_2` sufficient name, or should this be called something like `parse_lossy`?
- I made all of the commands work without fail in lossy mode, however, maybe some should fail?
- Should `from_32_2` `from_64_2` on `Segment` be exposed to the public? I currently have it `pub(crate)`.

2024-01-08 00:46 UTC, m4b requested changes
interesting PR, thank you! so as per the comments, I don't want to expose a `parse_2` name publicly, needs to be `parse` and `parse_lossy` or something, with the `parse_impl` getting forwarded whether it's lossy or not.

the only other consideration is whether you want to think about future lossy parsing, where a config is passed in to the lossy form, and this determines which things get dropped/ignored, etc., though that might be overkill, i don't know.

I'm also not totally sold on the `lossy` name, but it's ok.

Some other random alternatives that are probably worse names:
1. strict/unstrict
2. infallible

all said and done lossy is probably the best name?

Elf also has a similar, but slightly orthogonal support for "lazy" parsing, which doesn't parse the whole thing, but iirc, this was ostensibly to allow infallible parsing when some parts are broken/let user decide if they want to fail or not, may want to look at that, so we have a more unified api/approach to lossy/infallible/lazy parsing?

2024-01-08 00:46 UTC, m4b commented on src/mach/mod.rs
> +    pub fn parse_2(bytes: &'a [u8], mut offset: usize, lossy: bool) -> error::Result<MachO<'a>> {
definitely don't want this name in the public api; also why is lossy a bool? generally having a bool in a public function is not the best due to boolean blindness.

2024-01-08 00:46 UTC, m4b commented on src/mach/segment.rs
> +    pub(crate) fn from_32_2(
i'd rename this `from_32_impl` or something, change it to private, and have `from_32` call it with the boolean flag = false, and `from_32_lossy` call it with true

2024-01-08 00:46 UTC, m4b commented on src/mach/mod.rs
> +    pub fn parse_2(bytes: &'a [u8], lossy: bool) -> error::Result<Self> {
ditto; i'd make this function, `fn parse_impl` or something, then have:
```rust
pub fn parse()

pub fn parse_lossy()
```

call the `impl` with the boolean value forwarded

2024-02-03 22:21 UTC, h33p commented
Thanks for review, finally got around addressing your comments. Please let me know if you need anything else.

2024-02-04 23:45 UTC, m4b approved these changes
Test would be nice for this if you have time, otherwise lgtm

2024-03-10 06:29 UTC, m4b commented
@h33p CI is failing on rustfmt

2024-03-10 07:27 UTC, m4b commented
once format fixed this is good to go

2024-03-27 14:44 UTC, h33p commented
This should be good to go now @m4b

2024-04-01 00:40 UTC, m4b approved these changes
thanks!

2024-04-01 00:41 UTC, merged

2024-04-01 00:42 UTC, m4b commented
note: non-breaking

2024-04-27 18:44 UTC, m4b commented
released in 0.8.1